// Language translations
// Detected locale: jsmaf.locale

export const lang: Record<string, string> = {
  // Main menu
  jailbreak: 'Jailbreak',
  payloadMenu: 'Payload Menu',
  config: 'Config',
  exit: 'Exit',
  back: 'Back',

  // Config options
  autoLapse: 'Auto Lapse',
  autoPoop: 'Auto Poop',
  autoClose: 'Auto Close',
  music: 'Music',
  jbBehavior: 'JB Behavior',
  jbBehaviorAuto: 'Auto Detect',
  jbBehaviorNetctrl: 'NetControl',
  jbBehaviorLapse: 'Lapse',

  // New config options
  theme: 'Theme',
  navSounds: 'Nav Sounds',
  retryCount: 'Retry Count',
  autoPayload: 'Auto Payload',

  // Stats
  totalAttempts: 'Total Attempts: ',
  successes: 'Successes: ',
  failures: 'Failures: ',
  successRate: 'Success Rate: ',
  failureRate: 'Failure Rate: ',
  resetStats: 'Reset Stats',

  // Loading
  loadingMainMenu: 'Loading main menu...',
  mainMenuLoaded: 'Main menu loaded',
  loadingConfig: 'Loading config UI...',
  configLoaded: 'Config UI loaded',

  // New screens
  systemInfo: 'System Info',
  logViewer: 'Log Viewer',
  fileBrowser: 'File Browser',
  loadingSystemInfo: 'Loading system info...',
  systemInfoLoaded: 'System info loaded',
  loadingLogViewer: 'Loading log viewer...',
  logViewerLoaded: 'Log viewer loaded',
  loadingFileBrowser: 'Loading file browser...',
  fileBrowserLoaded: 'File browser loaded',

  // System info panels
  systemPanel: 'SYSTEM',
  memoryPanel: 'MEMORY',
  statsPanel: 'STATISTICS',
  configPanel: 'CONFIGURATION',
  fwVersion: 'Firmware',
  jailbreakStatus: 'Jailbreak Status',
  jailbroken: 'JAILBROKEN',
  notJailbroken: 'Not Jailbroken',
  exploitEngine: 'Exploit Engine',
  userland: 'Userland',
  availableMemory: 'Available',
  directMemory: 'Direct Memory',
  libcMemory: 'libc Memory',

  // Loader
  retrying: 'Retrying...',
  attempt: 'Attempt',
  of: 'of',
  memoryLow: 'Low memory warning!',
  exploitSuccess: 'Exploit Successful!',
  exploitFailed: 'Exploit Failed',
  alreadyJailbroken: 'Already Jailbroken!',

  // Payload favorites
  favorites: 'Favorites',
  addFavorite: 'Add to Favorites',
  removeFavorite: 'Remove Favorite',

  // Tools screen
  tools: 'Tools',
  loadingTools: 'Loading tools...',
  toolsLoaded: 'Tools loaded',
  startFTP: 'Start FTP Server',
  startWebUI: 'Start Web Server',
  injectUSB: 'Inject from USB',
  injectHDD: 'Inject from HDD',
  networkLoader: 'Network Loader',
  blockUpdates: 'Block FW Updates',
  enableDebug: 'Enable Debug Settings',
  sendNotify: 'Send Notification',
  dumpInfo: 'Dump System Info',
  rebootPS4: 'Reboot PS4',
  restartApp: 'Restart App',
  ftpDesc: 'Access PS4 files from PC (port 1337)',
  webUIDesc: 'Manage PS4 from any browser',
  usbDesc: 'Scan USB for payloads (.elf/.bin/.js)',
  hddDesc: 'Load payload from /data/payloads',
  networkLoaderDesc: 'Send payload to PS4 IP:9021',
  blockUpdatesDesc: 'Prevent system firmware updates',
  enableDebugDesc: 'Unlock hidden Debug Settings menu',
  sendNotifyDesc: 'Send a custom PS4 notification',
  dumpInfoDesc: 'Save info to /data/system_info.txt',
  rebootDesc: 'Reboot the PS4 system',
  restartDesc: 'Restart Vue-After-Free',
  jbStatusReady: 'Status: Jailbroken - All tools available',
  jbStatusLocked: 'Status: Not jailbroken - Some tools locked',
  jbRequired: 'Jailbreak required for',
  // Fan Control
  fanControl: 'Fan Control',
  fanControlDesc: 'Set CPU temp threshold for fan speed',
  loadingFanControl: 'Loading fan control...',
  fanControlLoaded: 'Fan control loaded',
  currentTemp: 'CPU Temperature',
  fanThreshLow: 'Slow → Med Threshold',
  fanThreshHigh: 'Med → Fast Threshold',
  fanSlowSpeed: 'Slow Speed',
  fanMedSpeed: 'Medium Speed',
  fanFastSpeed: 'Fast Speed',
  fanFixMode: 'Fan Fix (after JB)',
  fanFixOff: 'Off',
  fanFixBuiltIn: 'Built-in ICC',
  fanFixLaunchApp: 'Launch Temp App',
  autoFanFix: 'Auto Fan Fix (after JB)',
  applyFanFix: 'APPLY FAN FIX NOW',
  saveSettings: 'SAVE SETTINGS',
  fanStatus: 'Fan Status:',
  fanCurve: 'Fan Curve (3 Tier):',
  tempNotAvailable: 'N/A'
}

export let useImageText = false
export let textImageBase = ''

const detectedLocale = jsmaf.locale || 'en'
log('Detected locale: ' + detectedLocale)

const IMAGE_TEXT_LOCALES = ['ar', 'ja', 'ko', 'zh']
if (IMAGE_TEXT_LOCALES.includes(detectedLocale)) {
  useImageText = true
  textImageBase = 'file:///../download0/img/text/' + detectedLocale + '/'
}

switch (detectedLocale) {
  case 'es':
    // Spanish
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Menu de Payloads'
    lang.config = 'Configuracion'
    lang.exit = 'Salir'
    lang.back = 'Volver'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Auto Cerrar'
    lang.music = 'Musica'
    lang.jbBehavior = 'Comportamiento JB'
    lang.jbBehaviorAuto = 'Auto Detectar'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Tema'
    lang.navSounds = 'Sonidos Nav'
    lang.retryCount = 'Reintentos'
    lang.autoPayload = 'Payload Auto'
    lang.totalAttempts = 'Intentos Totales: '
    lang.successes = 'Exitos: '
    lang.failures = 'Fallos: '
    lang.successRate = 'Tasa de Exito: '
    lang.failureRate = 'Tasa de Fallo: '
    lang.resetStats = 'Restablecer'
    lang.loadingMainMenu = 'Cargando menu principal...'
    lang.mainMenuLoaded = 'Menu principal cargado'
    lang.loadingConfig = 'Cargando configuracion...'
    lang.configLoaded = 'Configuracion cargada'
    lang.systemInfo = 'Info del Sistema'
    lang.logViewer = 'Visor de Logs'
    lang.fileBrowser = 'Explorador'
    lang.systemPanel = 'SISTEMA'
    lang.memoryPanel = 'MEMORIA'
    lang.statsPanel = 'ESTADISTICAS'
    lang.configPanel = 'CONFIGURACION'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Estado Jailbreak'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Sin Jailbreak'
    lang.exploitEngine = 'Motor de Exploit'
    lang.retrying = 'Reintentando...'
    lang.attempt = 'Intento'
    lang.of = 'de'
    lang.memoryLow = 'Advertencia: memoria baja!'
    lang.exploitSuccess = 'Exploit exitoso!'
    lang.exploitFailed = 'Exploit fallido'
    lang.alreadyJailbroken = 'Ya tiene Jailbreak!'
    lang.favorites = 'Favoritos'
    lang.addFavorite = 'Agregar Favorito'
    lang.removeFavorite = 'Quitar Favorito'
    lang.tools = 'Herramientas'
    lang.startFTP = 'Iniciar FTP'
    lang.startWebUI = 'Iniciar Web UI'
    lang.injectUSB = 'Inyectar desde USB'
    lang.injectHDD = 'Inyectar desde HDD'
    lang.networkLoader = 'Cargador de Red'
    lang.blockUpdates = 'Bloquear Actualizaciones'
    lang.enableDebug = 'Ajustes de Depuracion'
    lang.sendNotify = 'Enviar Notificacion'
    lang.dumpInfo = 'Exportar Info'
    lang.rebootPS4 = 'Reiniciar PS4'
    lang.restartApp = 'Reiniciar App'
    lang.jbStatusReady = 'Estado: Jailbroken - Todas las herramientas disponibles'
    lang.jbStatusLocked = 'Estado: Sin Jailbreak - Algunas herramientas bloqueadas'
    lang.jbRequired = 'Jailbreak necesario para'
    lang.fanControl = 'Control de Ventilador'
    lang.fanControlDesc = 'Ajustar umbral de temp para velocidad del ventilador'
    lang.loadingFanControl = 'Cargando control de ventilador...'
    lang.fanControlLoaded = 'Control de ventilador cargado'
    lang.currentTemp = 'Temperatura CPU'
    lang.fanThreshLow = 'Umbral Lento → Medio'
    lang.fanThreshHigh = 'Umbral Medio → Rapido'
    lang.fanSlowSpeed = 'Velocidad Lenta'
    lang.fanMedSpeed = 'Velocidad Media'
    lang.fanFastSpeed = 'Velocidad Rapida'
    lang.fanFixMode = 'Fix Vent (post JB)'
    lang.fanFixOff = 'Desactivado'
    lang.fanFixBuiltIn = 'ICC Integrado'
    lang.fanFixLaunchApp = 'Abrir App Temp'
    lang.autoFanFix = 'Auto Fix Vent (post JB)'
    lang.applyFanFix = 'APLICAR AHORA'
    lang.saveSettings = 'GUARDAR'
    lang.fanStatus = 'Estado Ventilador:'
    lang.fanCurve = 'Curva (3 Niveles):'
    lang.tempNotAvailable = 'N/D'
    break

  case 'pt':
    // Portuguese
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Menu de Payloads'
    lang.config = 'Configuracao'
    lang.exit = 'Sair'
    lang.back = 'Voltar'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Fechar Auto'
    lang.music = 'Musica'
    lang.jbBehavior = 'Comportamento JB'
    lang.jbBehaviorAuto = 'Auto Detectar'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Tema'
    lang.navSounds = 'Sons Nav'
    lang.retryCount = 'Tentativas'
    lang.autoPayload = 'Payload Auto'
    lang.totalAttempts = 'Total de Tentativas: '
    lang.successes = 'Sucessos: '
    lang.failures = 'Falhas: '
    lang.successRate = 'Taxa de Sucesso: '
    lang.failureRate = 'Taxa de Falha: '
    lang.resetStats = 'Redefinir'
    lang.loadingMainMenu = 'Carregando menu principal...'
    lang.mainMenuLoaded = 'Menu principal carregado'
    lang.loadingConfig = 'Carregando configuracao...'
    lang.configLoaded = 'Configuracao carregada'
    lang.systemInfo = 'Info do Sistema'
    lang.logViewer = 'Visor de Logs'
    lang.fileBrowser = 'Explorador'
    lang.systemPanel = 'SISTEMA'
    lang.memoryPanel = 'MEMORIA'
    lang.statsPanel = 'ESTATISTICAS'
    lang.configPanel = 'CONFIGURACAO'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Status Jailbreak'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Sem Jailbreak'
    lang.retrying = 'Tentando novamente...'
    lang.attempt = 'Tentativa'
    lang.of = 'de'
    lang.memoryLow = 'Aviso: memoria baixa!'
    lang.exploitSuccess = 'Exploit bem-sucedido!'
    lang.exploitFailed = 'Exploit falhou'
    lang.alreadyJailbroken = 'Ja tem Jailbreak!'
    lang.favorites = 'Favoritos'
    lang.addFavorite = 'Adicionar Favorito'
    lang.removeFavorite = 'Remover Favorito'
    lang.tools = 'Ferramentas'
    lang.startFTP = 'Iniciar FTP'
    lang.startWebUI = 'Iniciar Web UI'
    lang.injectUSB = 'Injetar do USB'
    lang.injectHDD = 'Injetar do HDD'
    lang.networkLoader = 'Carregador de Rede'
    lang.blockUpdates = 'Bloquear Atualizacoes'
    lang.enableDebug = 'Config. de Depuracao'
    lang.sendNotify = 'Enviar Notificacao'
    lang.dumpInfo = 'Exportar Info'
    lang.rebootPS4 = 'Reiniciar PS4'
    lang.restartApp = 'Reiniciar App'
    lang.jbStatusReady = 'Status: Jailbroken - Todas ferramentas disponiveis'
    lang.jbStatusLocked = 'Status: Sem Jailbreak - Algumas ferramentas bloqueadas'
    lang.jbRequired = 'Jailbreak necessario para'
    lang.fanControl = 'Controle de Ventilador'
    lang.fanControlDesc = 'Definir limite de temp para velocidade do ventilador'
    lang.loadingFanControl = 'Carregando controle de ventilador...'
    lang.fanControlLoaded = 'Controle de ventilador carregado'
    lang.currentTemp = 'Temperatura CPU'
    lang.fanThreshLow = 'Umbral Lento → Medio'
    lang.fanThreshHigh = 'Umbral Medio → Rapido'
    lang.fanSlowSpeed = 'Velocidade Lenta'
    lang.fanMedSpeed = 'Velocidade Media'
    lang.fanFastSpeed = 'Velocidade Rapida'
    lang.fanFixMode = 'Fix Vent (pos JB)'
    lang.fanFixOff = 'Desligado'
    lang.fanFixBuiltIn = 'ICC Integrado'
    lang.fanFixLaunchApp = 'Abrir App Temp'
    lang.autoFanFix = 'Auto Fix Vent (pos JB)'
    lang.applyFanFix = 'APLICAR AGORA'
    lang.saveSettings = 'SALVAR'
    lang.fanStatus = 'Estado Ventilador:'
    lang.fanCurve = 'Curva (3 Niveis):'
    lang.tempNotAvailable = 'N/D'
    break

  case 'fr':
    // French
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Menu Payload'
    lang.config = 'Configuration'
    lang.exit = 'Quitter'
    lang.back = 'Retour'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Fermer Auto'
    lang.music = 'Musique'
    lang.jbBehavior = 'Comportement JB'
    lang.jbBehaviorAuto = 'Auto Detecter'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Theme'
    lang.navSounds = 'Sons Nav'
    lang.retryCount = 'Tentatives'
    lang.autoPayload = 'Payload Auto'
    lang.totalAttempts = 'Tentatives Totales: '
    lang.successes = 'Succes: '
    lang.failures = 'Echecs: '
    lang.successRate = 'Taux de Succes: '
    lang.failureRate = 'Taux Echec: '
    lang.resetStats = 'Reinitialiser'
    lang.loadingMainMenu = 'Chargement du menu principal...'
    lang.mainMenuLoaded = 'Menu principal charge'
    lang.loadingConfig = 'Chargement de la configuration...'
    lang.configLoaded = 'Configuration chargee'
    lang.systemInfo = 'Info Systeme'
    lang.logViewer = 'Journal'
    lang.fileBrowser = 'Explorateur'
    lang.systemPanel = 'SYSTEME'
    lang.memoryPanel = 'MEMOIRE'
    lang.statsPanel = 'STATISTIQUES'
    lang.configPanel = 'CONFIGURATION'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Statut Jailbreak'
    lang.jailbroken = 'JAILBREAKE'
    lang.notJailbroken = 'Non Jailbreake'
    lang.retrying = 'Nouvelle tentative...'
    lang.attempt = 'Tentative'
    lang.of = 'sur'
    lang.memoryLow = 'Attention: memoire faible!'
    lang.exploitSuccess = 'Exploit reussi!'
    lang.exploitFailed = 'Exploit echoue'
    lang.alreadyJailbroken = 'Deja Jailbreake!'
    lang.favorites = 'Favoris'
    lang.addFavorite = 'Ajouter Favori'
    lang.removeFavorite = 'Retirer Favori'
    lang.tools = 'Outils'
    lang.startFTP = 'Demarrer FTP'
    lang.startWebUI = 'Demarrer Web UI'
    lang.injectUSB = 'Injecter depuis USB'
    lang.injectHDD = 'Injecter depuis HDD'
    lang.networkLoader = 'Chargeur Reseau'
    lang.blockUpdates = 'Bloquer Mises a Jour'
    lang.enableDebug = 'Parametres Debug'
    lang.sendNotify = 'Envoyer Notification'
    lang.dumpInfo = 'Exporter Info'
    lang.rebootPS4 = 'Redemarrer PS4'
    lang.restartApp = 'Redemarrer App'
    lang.jbStatusReady = 'Statut: Jailbreake - Tous les outils disponibles'
    lang.jbStatusLocked = 'Statut: Non Jailbreake - Certains outils bloques'
    lang.jbRequired = 'Jailbreak requis pour'
    lang.fanControl = 'Controle Ventilateur'
    lang.fanControlDesc = 'Definir seuil de temp pour vitesse du ventilateur'
    lang.loadingFanControl = 'Chargement controle ventilateur...'
    lang.fanControlLoaded = 'Controle ventilateur charge'
    lang.currentTemp = 'Temperature CPU'
    lang.fanThreshLow = 'Seuil Lent → Moyen'
    lang.fanThreshHigh = 'Seuil Moyen → Rapide'
    lang.fanSlowSpeed = 'Vitesse Lente'
    lang.fanMedSpeed = 'Vitesse Moyenne'
    lang.fanFastSpeed = 'Vitesse Rapide'
    lang.fanFixMode = 'Fix Vent (apres JB)'
    lang.fanFixOff = 'Desactive'
    lang.fanFixBuiltIn = 'ICC Integre'
    lang.fanFixLaunchApp = 'Ouvrir App Temp'
    lang.autoFanFix = 'Auto Fix Vent (apres JB)'
    lang.applyFanFix = 'APPLIQUER MAINTENANT'
    lang.saveSettings = 'SAUVEGARDER'
    lang.fanStatus = 'Etat Ventilateur:'
    lang.fanCurve = 'Courbe (3 Niveaux):'
    lang.tempNotAvailable = 'N/D'
    break

  case 'de':
    // German
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Payload Menu'
    lang.config = 'Einstellungen'
    lang.exit = 'Beenden'
    lang.back = 'Zuruck'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Auto Schliessen'
    lang.music = 'Musik'
    lang.jbBehavior = 'JB Verhalten'
    lang.jbBehaviorAuto = 'Auto Erkennen'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Thema'
    lang.navSounds = 'Nav Tone'
    lang.retryCount = 'Wiederholungen'
    lang.autoPayload = 'Auto Payload'
    lang.totalAttempts = 'Gesamtversuche: '
    lang.successes = 'Erfolge: '
    lang.failures = 'Fehlschlage: '
    lang.successRate = 'Erfolgsrate: '
    lang.failureRate = 'Fehlerrate: '
    lang.resetStats = 'Zurucksetzen'
    lang.loadingMainMenu = 'Hauptmenu wird geladen...'
    lang.mainMenuLoaded = 'Hauptmenu geladen'
    lang.loadingConfig = 'Einstellungen werden geladen...'
    lang.configLoaded = 'Einstellungen geladen'
    lang.systemInfo = 'Systeminfo'
    lang.logViewer = 'Log Anzeige'
    lang.fileBrowser = 'Dateibrowser'
    lang.systemPanel = 'SYSTEM'
    lang.memoryPanel = 'SPEICHER'
    lang.statsPanel = 'STATISTIKEN'
    lang.configPanel = 'KONFIGURATION'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Jailbreak Status'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Kein Jailbreak'
    lang.retrying = 'Erneuter Versuch...'
    lang.attempt = 'Versuch'
    lang.of = 'von'
    lang.memoryLow = 'Warnung: wenig Speicher!'
    lang.exploitSuccess = 'Exploit erfolgreich!'
    lang.exploitFailed = 'Exploit fehlgeschlagen'
    lang.alreadyJailbroken = 'Bereits Jailbroken!'
    lang.favorites = 'Favoriten'
    lang.addFavorite = 'Favorit hinzufugen'
    lang.removeFavorite = 'Favorit entfernen'
    lang.tools = 'Werkzeuge'
    lang.startFTP = 'FTP starten'
    lang.startWebUI = 'Web UI starten'
    lang.injectUSB = 'Von USB injizieren'
    lang.injectHDD = 'Von HDD injizieren'
    lang.networkLoader = 'Netzwerk Loader'
    lang.blockUpdates = 'Updates blockieren'
    lang.enableDebug = 'Debug Einstellungen'
    lang.sendNotify = 'Benachrichtigung'
    lang.dumpInfo = 'Info exportieren'
    lang.rebootPS4 = 'PS4 neustarten'
    lang.restartApp = 'App neustarten'
    lang.jbStatusReady = 'Status: Jailbroken - Alle Tools verfugbar'
    lang.jbStatusLocked = 'Status: Kein Jailbreak - Einige Tools gesperrt'
    lang.jbRequired = 'Jailbreak erforderlich fur'
    lang.fanControl = 'Lufter Steuerung'
    lang.fanControlDesc = 'CPU-Temp Schwelle fur Luftergeschwindigkeit'
    lang.loadingFanControl = 'Lade Luftersteuerung...'
    lang.fanControlLoaded = 'Luftersteuerung geladen'
    lang.currentTemp = 'CPU Temperatur'
    lang.fanThreshLow = 'Schwelle Langsam → Mittel'
    lang.fanThreshHigh = 'Schwelle Mittel → Schnell'
    lang.fanSlowSpeed = 'Langsam'
    lang.fanMedSpeed = 'Mittel'
    lang.fanFastSpeed = 'Schnell'
    lang.fanFixMode = 'Lufter Fix (nach JB)'
    lang.fanFixOff = 'Aus'
    lang.fanFixBuiltIn = 'ICC Integriert'
    lang.fanFixLaunchApp = 'Temp App Starten'
    lang.autoFanFix = 'Auto Lufter Fix (nach JB)'
    lang.applyFanFix = 'JETZT ANWENDEN'
    lang.saveSettings = 'SPEICHERN'
    lang.fanStatus = 'Lufter Status:'
    lang.fanCurve = 'Lufter Kurve (3 Stufen):'
    lang.tempNotAvailable = 'N/V'
    break

  case 'it':
    // Italian
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Menu Payload'
    lang.config = 'Configurazione'
    lang.exit = 'Esci'
    lang.back = 'Indietro'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Chiudi Auto'
    lang.music = 'Musica'
    lang.jbBehavior = 'Comportamento JB'
    lang.jbBehaviorAuto = 'Auto Rileva'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Tema'
    lang.navSounds = 'Suoni Nav'
    lang.retryCount = 'Tentativi'
    lang.autoPayload = 'Payload Auto'
    lang.totalAttempts = 'Tentativi Totali: '
    lang.successes = 'Successi: '
    lang.failures = 'Fallimenti: '
    lang.successRate = 'Tasso di Successo: '
    lang.failureRate = 'Tasso di Fallimento: '
    lang.resetStats = 'Ripristina'
    lang.loadingMainMenu = 'Caricamento menu principale...'
    lang.mainMenuLoaded = 'Menu principale caricato'
    lang.loadingConfig = 'Caricamento configurazione...'
    lang.configLoaded = 'Configurazione caricata'
    lang.systemInfo = 'Info Sistema'
    lang.logViewer = 'Visualizzatore Log'
    lang.fileBrowser = 'Esplora File'
    lang.systemPanel = 'SISTEMA'
    lang.memoryPanel = 'MEMORIA'
    lang.statsPanel = 'STATISTICHE'
    lang.configPanel = 'CONFIGURAZIONE'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Stato Jailbreak'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Non Jailbroken'
    lang.retrying = 'Riprovando...'
    lang.attempt = 'Tentativo'
    lang.of = 'di'
    lang.memoryLow = 'Attenzione: memoria bassa!'
    lang.exploitSuccess = 'Exploit riuscito!'
    lang.exploitFailed = 'Exploit fallito'
    lang.alreadyJailbroken = 'Gia Jailbroken!'
    lang.favorites = 'Preferiti'
    lang.addFavorite = 'Aggiungi Preferito'
    lang.removeFavorite = 'Rimuovi Preferito'
    lang.tools = 'Strumenti'
    lang.startFTP = 'Avvia FTP'
    lang.startWebUI = 'Avvia Web UI'
    lang.injectUSB = 'Iniettare da USB'
    lang.injectHDD = 'Iniettare da HDD'
    lang.networkLoader = 'Caricatore Rete'
    lang.blockUpdates = 'Blocca Aggiornamenti'
    lang.enableDebug = 'Impostazioni Debug'
    lang.sendNotify = 'Invia Notifica'
    lang.dumpInfo = 'Esporta Info'
    lang.rebootPS4 = 'Riavvia PS4'
    lang.restartApp = 'Riavvia App'
    lang.jbStatusReady = 'Stato: Jailbroken - Tutti gli strumenti disponibili'
    lang.jbStatusLocked = 'Stato: Non Jailbroken - Alcuni strumenti bloccati'
    lang.jbRequired = 'Jailbreak necessario per'
    lang.fanControl = 'Controllo Ventola'
    lang.fanControlDesc = 'Imposta soglia temp per velocita ventola'
    lang.loadingFanControl = 'Caricamento controllo ventola...'
    lang.fanControlLoaded = 'Controllo ventola caricato'
    lang.currentTemp = 'Temperatura CPU'
    lang.fanThreshLow = 'Soglia Lento → Medio'
    lang.fanThreshHigh = 'Soglia Medio → Veloce'
    lang.fanSlowSpeed = 'Velocita Lenta'
    lang.fanMedSpeed = 'Velocita Media'
    lang.fanFastSpeed = 'Velocita Veloce'
    lang.fanFixMode = 'Fix Ventola (dopo JB)'
    lang.fanFixOff = 'Spento'
    lang.fanFixBuiltIn = 'ICC Integrato'
    lang.fanFixLaunchApp = 'Apri App Temp'
    lang.autoFanFix = 'Auto Fix Ventola (dopo JB)'
    lang.applyFanFix = 'APPLICA ORA'
    lang.saveSettings = 'SALVA'
    lang.fanStatus = 'Stato Ventola:'
    lang.fanCurve = 'Curva (3 Livelli):'
    lang.tempNotAvailable = 'N/D'
    break

  case 'nl':
    // Dutch
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Payload Menu'
    lang.config = 'Instellingen'
    lang.exit = 'Afsluiten'
    lang.back = 'Terug'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Auto Sluiten'
    lang.music = 'Muziek'
    lang.jbBehavior = 'JB Gedrag'
    lang.jbBehaviorAuto = 'Auto Detectie'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Thema'
    lang.navSounds = 'Nav Geluiden'
    lang.retryCount = 'Pogingen'
    lang.autoPayload = 'Auto Payload'
    lang.totalAttempts = 'Totaal Pogingen: '
    lang.successes = 'Successen: '
    lang.failures = 'Mislukkingen: '
    lang.successRate = 'Succespercentage: '
    lang.failureRate = 'Faalpercentage: '
    lang.resetStats = 'Resetten'
    lang.loadingMainMenu = 'Hoofdmenu laden...'
    lang.mainMenuLoaded = 'Hoofdmenu geladen'
    lang.loadingConfig = 'Instellingen laden...'
    lang.configLoaded = 'Instellingen geladen'
    lang.systemInfo = 'Systeeminfo'
    lang.logViewer = 'Log Viewer'
    lang.fileBrowser = 'Bestandsbrowser'
    lang.systemPanel = 'SYSTEEM'
    lang.memoryPanel = 'GEHEUGEN'
    lang.statsPanel = 'STATISTIEKEN'
    lang.configPanel = 'CONFIGURATIE'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Jailbreak Status'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Niet Jailbroken'
    lang.retrying = 'Opnieuw proberen...'
    lang.attempt = 'Poging'
    lang.of = 'van'
    lang.memoryLow = 'Waarschuwing: weinig geheugen!'
    lang.exploitSuccess = 'Exploit geslaagd!'
    lang.exploitFailed = 'Exploit mislukt'
    lang.alreadyJailbroken = 'Al Jailbroken!'
    lang.favorites = 'Favorieten'
    lang.addFavorite = 'Favoriet Toevoegen'
    lang.removeFavorite = 'Favoriet Verwijderen'
    lang.tools = 'Gereedschap'
    lang.startFTP = 'FTP Starten'
    lang.startWebUI = 'Web UI Starten'
    lang.injectUSB = 'Laden van USB'
    lang.injectHDD = 'Laden van HDD'
    lang.networkLoader = 'Netwerk Lader'
    lang.blockUpdates = 'Updates Blokkeren'
    lang.enableDebug = 'Debug Instellingen'
    lang.sendNotify = 'Melding Sturen'
    lang.dumpInfo = 'Info Exporteren'
    lang.rebootPS4 = 'PS4 Herstarten'
    lang.restartApp = 'App Herstarten'
    lang.jbStatusReady = 'Status: Jailbroken - Alle tools beschikbaar'
    lang.jbStatusLocked = 'Status: Niet Jailbroken - Sommige tools vergrendeld'
    lang.jbRequired = 'Jailbreak vereist voor'
    lang.fanControl = 'Ventilator Bediening'
    lang.fanControlDesc = 'CPU temp drempel voor ventilatorsnelheid instellen'
    lang.loadingFanControl = 'Ventilator bediening laden...'
    lang.fanControlLoaded = 'Ventilator bediening geladen'
    lang.currentTemp = 'CPU Temperatuur'
    lang.fanThreshLow = 'Drempel Langzaam → Midden'
    lang.fanThreshHigh = 'Drempel Midden → Snel'
    lang.fanSlowSpeed = 'Langzaam'
    lang.fanMedSpeed = 'Midden'
    lang.fanFastSpeed = 'Snel'
    lang.fanFixMode = 'Vent Fix (na JB)'
    lang.fanFixOff = 'Uit'
    lang.fanFixBuiltIn = 'ICC Ingebouwd'
    lang.fanFixLaunchApp = 'Temp App Openen'
    lang.autoFanFix = 'Auto Vent Fix (na JB)'
    lang.applyFanFix = 'NU TOEPASSEN'
    lang.saveSettings = 'OPSLAAN'
    lang.fanStatus = 'Ventilator Status:'
    lang.fanCurve = 'Ventilator (3 Niveaus):'
    lang.tempNotAvailable = 'N/B'
    break

  case 'pl':
    // Polish
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Menu Payload'
    lang.config = 'Konfiguracja'
    lang.exit = 'Wyjscie'
    lang.back = 'Wstecz'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Auto Zamknij'
    lang.music = 'Muzyka'
    lang.jbBehavior = 'Zachowanie JB'
    lang.jbBehaviorAuto = 'Auto Wykryj'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Motyw'
    lang.navSounds = 'Dzwieki Nav'
    lang.retryCount = 'Proby'
    lang.autoPayload = 'Auto Payload'
    lang.totalAttempts = 'Laczna Liczba Prob: '
    lang.successes = 'Sukcesy: '
    lang.failures = 'Niepowodzenia: '
    lang.successRate = 'Wskaznik Sukcesu: '
    lang.failureRate = 'Wskaznik Bledow: '
    lang.resetStats = 'Resetuj'
    lang.loadingMainMenu = 'Ladowanie menu glownego...'
    lang.mainMenuLoaded = 'Menu glowne zaladowane'
    lang.loadingConfig = 'Ladowanie konfiguracji...'
    lang.configLoaded = 'Konfiguracja zaladowana'
    lang.systemInfo = 'Info o Systemie'
    lang.logViewer = 'Przegladarka Logow'
    lang.fileBrowser = 'Przegladarka Plikow'
    lang.systemPanel = 'SYSTEM'
    lang.memoryPanel = 'PAMIEC'
    lang.statsPanel = 'STATYSTYKI'
    lang.configPanel = 'KONFIGURACJA'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Status Jailbreak'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Brak Jailbreak'
    lang.retrying = 'Ponowna proba...'
    lang.attempt = 'Proba'
    lang.of = 'z'
    lang.memoryLow = 'Uwaga: malo pamieci!'
    lang.exploitSuccess = 'Exploit powiodl sie!'
    lang.exploitFailed = 'Exploit nie powiodl sie'
    lang.alreadyJailbroken = 'Juz Jailbroken!'
    lang.favorites = 'Ulubione'
    lang.addFavorite = 'Dodaj Ulubione'
    lang.removeFavorite = 'Usun Ulubione'
    lang.tools = 'Narzedzia'
    lang.startFTP = 'Uruchom FTP'
    lang.startWebUI = 'Uruchom Web UI'
    lang.injectUSB = 'Zaladuj z USB'
    lang.injectHDD = 'Zaladuj z HDD'
    lang.networkLoader = 'Ladowarka Sieciowa'
    lang.blockUpdates = 'Blokuj Aktualizacje'
    lang.enableDebug = 'Ustawienia Debug'
    lang.sendNotify = 'Wyslij Powiadomienie'
    lang.dumpInfo = 'Eksportuj Info'
    lang.rebootPS4 = 'Restart PS4'
    lang.restartApp = 'Uruchom ponownie'
    lang.jbStatusReady = 'Status: Jailbroken - Wszystkie narzedzia dostepne'
    lang.jbStatusLocked = 'Status: Brak Jailbreak - Niektore narzedzia zablokowane'
    lang.jbRequired = 'Jailbreak wymagany dla'
    lang.fanControl = 'Sterowanie Wentylatorem'
    lang.fanControlDesc = 'Ustaw prog temp CPU dla predkosci wentylatora'
    lang.loadingFanControl = 'Ladowanie sterowania wentylatorem...'
    lang.fanControlLoaded = 'Sterowanie wentylatorem zaladowane'
    lang.currentTemp = 'Temperatura CPU'
    lang.fanThreshLow = 'Prog Wolny → Sredni'
    lang.fanThreshHigh = 'Prog Sredni → Szybki'
    lang.fanSlowSpeed = 'Wolny'
    lang.fanMedSpeed = 'Sredni'
    lang.fanFastSpeed = 'Szybki'
    lang.fanFixMode = 'Fix Went (po JB)'
    lang.fanFixOff = 'Wyl'
    lang.fanFixBuiltIn = 'ICC Wbudowany'
    lang.fanFixLaunchApp = 'Otworz App Temp'
    lang.autoFanFix = 'Auto Fix Went (po JB)'
    lang.applyFanFix = 'ZASTOSUJ TERAZ'
    lang.saveSettings = 'ZAPISZ'
    lang.fanStatus = 'Status Wentylatora:'
    lang.fanCurve = 'Krzywa (3 Poziomy):'
    lang.tempNotAvailable = 'N/D'
    break

  case 'tr':
    // Turkish
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Payload Menusu'
    lang.config = 'Ayarlar'
    lang.exit = 'Cikis'
    lang.back = 'Geri'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Otomatik Kapat'
    lang.music = 'Muzik'
    lang.jbBehavior = 'JB Davranisi'
    lang.jbBehaviorAuto = 'Otomatik Algilama'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Tema'
    lang.navSounds = 'Nav Sesleri'
    lang.retryCount = 'Tekrar Sayisi'
    lang.autoPayload = 'Otomatik Payload'
    lang.totalAttempts = 'Toplam Deneme: '
    lang.successes = 'Basarilar: '
    lang.failures = 'Basarisizliklar: '
    lang.successRate = 'Basari Orani: '
    lang.failureRate = 'Basarisizlik Orani: '
    lang.resetStats = 'Sifirla'
    lang.loadingMainMenu = 'Ana menu yukleniyor...'
    lang.mainMenuLoaded = 'Ana menu yuklendi'
    lang.loadingConfig = 'Ayarlar yukleniyor...'
    lang.configLoaded = 'Ayarlar yuklendi'
    lang.systemInfo = 'Sistem Bilgisi'
    lang.logViewer = 'Log Goruntuleme'
    lang.fileBrowser = 'Dosya Gezgini'
    lang.systemPanel = 'SISTEM'
    lang.memoryPanel = 'BELLEK'
    lang.statsPanel = 'ISTATISTIKLER'
    lang.configPanel = 'YAPILANDIRMA'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Jailbreak Durumu'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Jailbreak Yok'
    lang.retrying = 'Tekrar deneniyor...'
    lang.attempt = 'Deneme'
    lang.of = '/'
    lang.memoryLow = 'Uyari: dusuk bellek!'
    lang.exploitSuccess = 'Exploit basarili!'
    lang.exploitFailed = 'Exploit basarisiz'
    lang.alreadyJailbroken = 'Zaten Jailbroken!'
    lang.favorites = 'Favoriler'
    lang.addFavorite = 'Favori Ekle'
    lang.removeFavorite = 'Favori Kaldir'
    lang.tools = 'Araclar'
    lang.startFTP = 'FTP Baslat'
    lang.startWebUI = 'Web UI Baslat'
    lang.injectUSB = 'USB den Yukle'
    lang.injectHDD = 'HDD den Yukle'
    lang.networkLoader = 'Ag Yukleyici'
    lang.blockUpdates = 'Guncellemeleri Engelle'
    lang.enableDebug = 'Debug Ayarlari'
    lang.sendNotify = 'Bildirim Gonder'
    lang.dumpInfo = 'Bilgi Aktar'
    lang.rebootPS4 = 'PS4 Yeniden Baslat'
    lang.restartApp = 'Uygulamayi Yeniden Baslat'
    lang.jbStatusReady = 'Durum: Jailbroken - Tum araclar mevcut'
    lang.jbStatusLocked = 'Durum: Jailbreak Yok - Bazi araclar kilitli'
    lang.jbRequired = 'Jailbreak gerekli:'
    lang.fanControl = 'Fan Kontrolu'
    lang.fanControlDesc = 'CPU sicaklik esigi ile fan hizi ayarla'
    lang.loadingFanControl = 'Fan kontrolu yukleniyor...'
    lang.fanControlLoaded = 'Fan kontrolu yuklendi'
    lang.currentTemp = 'CPU Sicakligi'
    lang.fanThreshLow = 'Esik Yavas → Orta'
    lang.fanThreshHigh = 'Esik Orta → Hizli'
    lang.fanSlowSpeed = 'Yavas'
    lang.fanMedSpeed = 'Orta'
    lang.fanFastSpeed = 'Hizli'
    lang.fanFixMode = 'Fan Fix (JB sonrasi)'
    lang.fanFixOff = 'Kapali'
    lang.fanFixBuiltIn = 'ICC Dahili'
    lang.fanFixLaunchApp = 'Temp App Ac'
    lang.autoFanFix = 'Oto Fan Fix (JB sonrasi)'
    lang.applyFanFix = 'SIMDI UYGULA'
    lang.saveSettings = 'KAYDET'
    lang.fanStatus = 'Fan Durumu:'
    lang.fanCurve = 'Fan Egrisi (3 Seviye):'
    lang.tempNotAvailable = 'Yok'
    break

  case 'ru':
    // Russian (Latin transliteration for PS4 font compatibility)
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Payload Menu'
    lang.config = 'Nastroyki'
    lang.exit = 'Vykhod'
    lang.back = 'Nazad'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Auto Zakryt'
    lang.music = 'Muzyka'
    lang.jbBehavior = 'JB Povedenie'
    lang.jbBehaviorAuto = 'Auto Opredelenie'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Tema'
    lang.navSounds = 'Nav Zvuki'
    lang.retryCount = 'Popytki'
    lang.autoPayload = 'Auto Payload'
    lang.totalAttempts = 'Vsego Popytok: '
    lang.successes = 'Uspeshno: '
    lang.failures = 'Neudach: '
    lang.successRate = 'Uspeshnost: '
    lang.failureRate = 'Neudach %: '
    lang.resetStats = 'Sbrosit'
    lang.loadingMainMenu = 'Zagruzka menu...'
    lang.mainMenuLoaded = 'Menu zagruzheno'
    lang.loadingConfig = 'Zagruzka nastroek...'
    lang.configLoaded = 'Nastroyki zagruzheny'
    lang.systemInfo = 'Info o Sisteme'
    lang.logViewer = 'Prosmotr Logov'
    lang.fileBrowser = 'Faily'
    lang.systemPanel = 'SISTEMA'
    lang.memoryPanel = 'PAMYAT'
    lang.statsPanel = 'STATISTIKA'
    lang.configPanel = 'NASTROYKI'
    lang.fwVersion = 'Firmware'
    lang.jailbreakStatus = 'Status Jailbreak'
    lang.jailbroken = 'JAILBROKEN'
    lang.notJailbroken = 'Net Jailbreak'
    lang.retrying = 'Povtornaya popytka...'
    lang.attempt = 'Popytka'
    lang.of = 'iz'
    lang.memoryLow = 'Vnimanie: malo pamyati!'
    lang.exploitSuccess = 'Exploit uspeshen!'
    lang.exploitFailed = 'Exploit ne udalsya'
    lang.alreadyJailbroken = 'Uzhe Jailbroken!'
    lang.favorites = 'Izbrannoe'
    lang.addFavorite = 'Dobavit'
    lang.removeFavorite = 'Udalit'
    lang.tools = 'Instrumenty'
    lang.startFTP = 'Zapustit FTP'
    lang.startWebUI = 'Zapustit Web UI'
    lang.injectUSB = 'Zagruzit s USB'
    lang.injectHDD = 'Zagruzit s HDD'
    lang.networkLoader = 'Setevoy zagruzchik'
    lang.blockUpdates = 'Blokirovat obnovleniya'
    lang.enableDebug = 'Nastroyki otladki'
    lang.sendNotify = 'Otpravit uvedomlenie'
    lang.dumpInfo = 'Eksport Info'
    lang.rebootPS4 = 'Perezagruzit PS4'
    lang.restartApp = 'Perezapustit'
    lang.jbStatusReady = 'Status: Jailbroken - Vse instrumenty dostupny'
    lang.jbStatusLocked = 'Status: Net Jailbreak - Nekotorye instrumenty zablokirovany'
    lang.jbRequired = 'Jailbreak neobhodim dlya'
    lang.fanControl = 'Upravlenie Ventilyatorom'
    lang.fanControlDesc = 'Porog temp CPU dlya skorosti ventilyatora'
    lang.loadingFanControl = 'Zagruzka upravleniya ventilyatorom...'
    lang.fanControlLoaded = 'Upravlenie ventilyatorom zagruzheno'
    lang.currentTemp = 'Temperatura CPU'
    lang.fanThreshLow = 'Porog Medlenno → Sredniy'
    lang.fanThreshHigh = 'Porog Sredniy → Bystro'
    lang.fanSlowSpeed = 'Medlenno'
    lang.fanMedSpeed = 'Sredniy'
    lang.fanFastSpeed = 'Bystro'
    lang.fanFixMode = 'Fix Vent (posle JB)'
    lang.fanFixOff = 'Vykl'
    lang.fanFixBuiltIn = 'ICC Vstroennyy'
    lang.fanFixLaunchApp = 'Otkryt Temp App'
    lang.autoFanFix = 'Avto Fix Vent (posle JB)'
    lang.applyFanFix = 'PRIMENIT SEYCHAS'
    lang.saveSettings = 'SOKHRANIT'
    lang.fanStatus = 'Status Ventilyatora:'
    lang.fanCurve = 'Krivaya (3 Urovnya):'
    lang.tempNotAvailable = 'N/D'
    break

  case 'vi':
    // Vietnamese
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'Menu Payload'
    lang.config = 'Cau hinh'
    lang.exit = 'Thoat'
    lang.back = 'Quay lai'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'Tu dong dong'
    lang.music = 'Am nhac'
    lang.jbBehavior = 'JB Hanh vi'
    lang.jbBehaviorAuto = 'Tu dong'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'Giao dien'
    lang.navSounds = 'Am thanh'
    lang.retryCount = 'So lan thu'
    lang.autoPayload = 'Auto Payload'
    lang.totalAttempts = 'Tong so lan: '
    lang.successes = 'Thanh cong: '
    lang.failures = 'That bai: '
    lang.successRate = 'Ti le TC: '
    lang.failureRate = 'Ti le TB: '
    lang.resetStats = 'Dat lai'
    lang.loadingMainMenu = 'Dang tai menu...'
    lang.mainMenuLoaded = 'Menu da tai'
    lang.loadingConfig = 'Dang tai cau hinh...'
    lang.configLoaded = 'Cau hinh da tai'
    lang.systemInfo = 'Thong tin He thong'
    lang.logViewer = 'Xem Log'
    lang.fileBrowser = 'Duyet File'
    lang.systemPanel = 'HE THONG'
    lang.memoryPanel = 'BO NHO'
    lang.statsPanel = 'THONG KE'
    lang.configPanel = 'CAU HINH'
    lang.retrying = 'Dang thu lai...'
    lang.attempt = 'Lan thu'
    lang.of = '/'
    lang.memoryLow = 'Canh bao: it bo nho!'
    lang.exploitSuccess = 'Exploit thanh cong!'
    lang.exploitFailed = 'Exploit that bai'
    lang.alreadyJailbroken = 'Da Jailbreak roi!'
    lang.favorites = 'Yeu thich'
    lang.addFavorite = 'Them'
    lang.removeFavorite = 'Xoa'
    lang.tools = 'Cong cu'
    lang.startFTP = 'Khoi dong FTP'
    lang.startWebUI = 'Khoi dong Web UI'
    lang.injectUSB = 'Nap tu USB'
    lang.injectHDD = 'Nap tu HDD'
    lang.networkLoader = 'Nap qua mang'
    lang.blockUpdates = 'Chan cap nhat'
    lang.enableDebug = 'Bat Debug'
    lang.sendNotify = 'Gui thong bao'
    lang.dumpInfo = 'Xuat thong tin'
    lang.rebootPS4 = 'Khoi dong lai PS4'
    lang.restartApp = 'Khoi dong lai ung dung'
    lang.jbStatusReady = 'Trang thai: Jailbroken - Tat ca cong cu san sang'
    lang.jbStatusLocked = 'Trang thai: Chua Jailbreak - Mot so cong cu bi khoa'
    lang.jbRequired = 'Can Jailbreak de su dung'
    lang.fanControl = 'Dieu Khien Quat'
    lang.fanControlDesc = 'Dat nguong nhiet do CPU cho toc do quat'
    lang.loadingFanControl = 'Dang tai dieu khien quat...'
    lang.fanControlLoaded = 'Dieu khien quat da tai'
    lang.currentTemp = 'Nhiet Do CPU'
    lang.fanThreshLow = 'Nguong Cham → Trung Binh'
    lang.fanThreshHigh = 'Nguong Trung Binh → Nhanh'
    lang.fanSlowSpeed = 'Cham'
    lang.fanMedSpeed = 'Trung Binh'
    lang.fanFastSpeed = 'Nhanh'
    lang.fanFixMode = 'Fix Quat (sau JB)'
    lang.fanFixOff = 'Tat'
    lang.fanFixBuiltIn = 'ICC Tich Hop'
    lang.fanFixLaunchApp = 'Mo App Nhiet'
    lang.autoFanFix = 'Tu Dong Fix Quat (sau JB)'
    lang.applyFanFix = 'AP DUNG NGAY'
    lang.saveSettings = 'LUU CAI DAT'
    lang.fanStatus = 'Trang Thai Quat:'
    lang.fanCurve = 'Duong Cong (3 Muc):'
    lang.tempNotAvailable = 'K/D'
    break

  case 'ar':
    // Arabic
    lang.jailbreak = 'Jailbreak'
    lang.payloadMenu = 'قائمة الحمولة'
    lang.config = 'الاعدادات'
    lang.exit = 'خروج'
    lang.back = 'رجوع'
    lang.autoLapse = 'Auto Lapse'
    lang.autoPoop = 'Auto Poop'
    lang.autoClose = 'اغلاق تلقائي'
    lang.music = 'موسيقى'
    lang.jbBehavior = 'سلوك JB'
    lang.jbBehaviorAuto = 'كشف تلقائي'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'السمة'
    lang.navSounds = 'اصوات'
    lang.retryCount = 'محاولات'
    lang.autoPayload = 'تلقائي'
    lang.totalAttempts = 'اجمالي المحاولات: '
    lang.successes = 'النجاحات: '
    lang.failures = 'الاخفاقات: '
    lang.successRate = 'معدل النجاح: '
    lang.failureRate = 'معدل الفشل: '
    lang.resetStats = 'اعادة'
    lang.loadingMainMenu = 'جاري تحميل القائمة الرئيسية...'
    lang.mainMenuLoaded = 'تم تحميل القائمة الرئيسية'
    lang.loadingConfig = 'جاري تحميل الاعدادات...'
    lang.configLoaded = 'تم تحميل الاعدادات'
    lang.systemInfo = 'معلومات النظام'
    lang.logViewer = 'عرض السجل'
    lang.fileBrowser = 'متصفح الملفات'
    lang.systemPanel = 'النظام'
    lang.memoryPanel = 'الذاكرة'
    lang.statsPanel = 'الاحصائيات'
    lang.configPanel = 'الاعدادات'
    lang.fanControl = 'التحكم بالمروحة'
    lang.fanControlDesc = 'ضبط حد درجة حرارة المعالج لسرعة المروحة'
    lang.currentTemp = 'درجة حرارة المعالج'
    lang.fanThreshLow = 'حد بطيء → متوسط'
    lang.fanThreshHigh = 'حد متوسط → سريع'
    lang.fanSlowSpeed = 'بطيء'
    lang.fanMedSpeed = 'متوسط'
    lang.fanFastSpeed = 'سريع'
    lang.fanFixMode = 'إصلاح المروحة (بعد JB)'
    lang.fanFixOff = 'إيقاف'
    lang.fanFixBuiltIn = 'ICC مدمج'
    lang.fanFixLaunchApp = 'فتح تطبيق الحرارة'
    lang.autoFanFix = 'إصلاح تلقائي للمروحة'
    lang.applyFanFix = 'تطبيق الآن'
    lang.saveSettings = 'حفظ'
    lang.fanStatus = 'حالة المروحة:'
    lang.fanCurve = 'منحنى (3 مستويات):'
    lang.tempNotAvailable = 'غير متوفر'
    break

  case 'ja':
    // Japanese
    lang.jailbreak = '脱獄'
    lang.payloadMenu = 'ペイロードメニュー'
    lang.config = '設定'
    lang.exit = '終了'
    lang.back = '戻る'
    lang.autoLapse = '自動Lapse'
    lang.autoPoop = '自動Poop'
    lang.autoClose = '自動終了'
    lang.music = '音楽'
    lang.jbBehavior = 'JB動作'
    lang.jbBehaviorAuto = '自動検出'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = 'テーマ'
    lang.navSounds = 'ナビ音'
    lang.retryCount = 'リトライ'
    lang.autoPayload = '自動ペイロード'
    lang.totalAttempts = '試行回数: '
    lang.successes = '成功: '
    lang.failures = '失敗: '
    lang.successRate = '成功率: '
    lang.failureRate = '失敗率: '
    lang.resetStats = 'リセット'
    lang.loadingMainMenu = 'メインメニュー読み込み中...'
    lang.mainMenuLoaded = 'メインメニュー読み込み完了'
    lang.loadingConfig = '設定読み込み中...'
    lang.configLoaded = '設定読み込み完了'
    lang.systemInfo = 'システム情報'
    lang.logViewer = 'ログビューア'
    lang.fileBrowser = 'ファイルブラウザ'
    lang.systemPanel = 'システム'
    lang.memoryPanel = 'メモリ'
    lang.statsPanel = '統計'
    lang.configPanel = '設定'
    lang.fanControl = 'ファン制御'
    lang.fanControlDesc = 'CPU温度閾値でファン速度を設定'
    lang.currentTemp = 'CPU温度'
    lang.fanThreshLow = '低速→中速 閾値'
    lang.fanThreshHigh = '中速→高速 閾値'
    lang.fanSlowSpeed = '低速'
    lang.fanMedSpeed = '中速'
    lang.fanFastSpeed = '高速'
    lang.fanFixMode = 'ファン修正（JB後）'
    lang.fanFixOff = 'オフ'
    lang.fanFixBuiltIn = 'ICC内蔵'
    lang.fanFixLaunchApp = '温度アプリ起動'
    lang.autoFanFix = '自動ファン修正（JB後）'
    lang.applyFanFix = '今すぐ適用'
    lang.saveSettings = '保存'
    lang.fanStatus = 'ファン状態:'
    lang.fanCurve = 'ファンカーブ(3段階):'
    lang.tempNotAvailable = '不明'
    break

  case 'ko':
    // Korean
    lang.jailbreak = '탈옥'
    lang.payloadMenu = '페이로드 메뉴'
    lang.config = '설정'
    lang.exit = '종료'
    lang.back = '뒤로'
    lang.autoLapse = '자동 Lapse'
    lang.autoPoop = '자동 Poop'
    lang.autoClose = '자동 닫기'
    lang.music = '음악'
    lang.jbBehavior = 'JB 동작'
    lang.jbBehaviorAuto = '자동 감지'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = '테마'
    lang.navSounds = '소리'
    lang.retryCount = '재시도'
    lang.autoPayload = '자동 페이로드'
    lang.totalAttempts = '총 시도: '
    lang.successes = '성공: '
    lang.failures = '실패: '
    lang.successRate = '성공률: '
    lang.failureRate = '실패율: '
    lang.resetStats = '초기화'
    lang.loadingMainMenu = '메인 메뉴 로딩중...'
    lang.mainMenuLoaded = '메인 메뉴 로딩 완료'
    lang.loadingConfig = '설정 로딩중...'
    lang.configLoaded = '설정 로딩 완료'
    lang.systemInfo = '시스템 정보'
    lang.logViewer = '로그 보기'
    lang.fileBrowser = '파일 탐색기'
    lang.systemPanel = '시스템'
    lang.memoryPanel = '메모리'
    lang.statsPanel = '통계'
    lang.configPanel = '설정'
    lang.fanControl = '팬 제어'
    lang.fanControlDesc = 'CPU 온도 임계값으로 팬 속도 설정'
    lang.currentTemp = 'CPU 온도'
    lang.fanThreshLow = '저속→중속 임계값'
    lang.fanThreshHigh = '중속→고속 임계값'
    lang.fanSlowSpeed = '저속'
    lang.fanMedSpeed = '중속'
    lang.fanFastSpeed = '고속'
    lang.fanFixMode = '팬 수정 (JB 후)'
    lang.fanFixOff = '끔'
    lang.fanFixBuiltIn = 'ICC 내장'
    lang.fanFixLaunchApp = '온도 앱 실행'
    lang.autoFanFix = '자동 팬 수정 (JB 후)'
    lang.applyFanFix = '지금 적용'
    lang.saveSettings = '저장'
    lang.fanStatus = '팬 상태:'
    lang.fanCurve = '팬 커브(3단계):'
    lang.tempNotAvailable = '불명'
    break

  case 'zh':
    // Chinese
    lang.jailbreak = '越狱'
    lang.payloadMenu = '载荷菜单'
    lang.config = '设置'
    lang.exit = '退出'
    lang.back = '返回'
    lang.autoLapse = '自动Lapse'
    lang.autoPoop = '自动Poop'
    lang.autoClose = '自动关闭'
    lang.music = '音乐'
    lang.jbBehavior = 'JB行为'
    lang.jbBehaviorAuto = '自动检测'
    lang.jbBehaviorNetctrl = 'NetControl'
    lang.jbBehaviorLapse = 'Lapse'
    lang.theme = '主题'
    lang.navSounds = '导航音效'
    lang.retryCount = '重试次数'
    lang.autoPayload = '自动载荷'
    lang.totalAttempts = '总尝试次数: '
    lang.successes = '成功: '
    lang.failures = '失败: '
    lang.successRate = '成功率: '
    lang.failureRate = '失败率: '
    lang.resetStats = '重置'
    lang.loadingMainMenu = '正在加载主菜单...'
    lang.mainMenuLoaded = '主菜单已加载'
    lang.loadingConfig = '正在加载设置...'
    lang.configLoaded = '设置已加载'
    lang.systemInfo = '系统信息'
    lang.logViewer = '日志查看'
    lang.fileBrowser = '文件浏览器'
    lang.systemPanel = '系统'
    lang.memoryPanel = '内存'
    lang.statsPanel = '统计'
    lang.configPanel = '配置'
    lang.fanControl = '风扇控制'
    lang.fanControlDesc = '设置CPU温度阈值控制风扇速度'
    lang.currentTemp = 'CPU温度'
    lang.fanThreshLow = '低速→中速 阈值'
    lang.fanThreshHigh = '中速→高速 阈值'
    lang.fanSlowSpeed = '低速'
    lang.fanMedSpeed = '中速'
    lang.fanFastSpeed = '高速'
    lang.fanFixMode = '风扇修复（JB后）'
    lang.fanFixOff = '关闭'
    lang.fanFixBuiltIn = 'ICC内置'
    lang.fanFixLaunchApp = '启动温度应用'
    lang.autoFanFix = '自动风扇修复（JB后）'
    lang.applyFanFix = '立即应用'
    lang.saveSettings = '保存设置'
    lang.fanStatus = '风扇状态:'
    lang.fanCurve = '风扇曲线(3级):'
    lang.tempNotAvailable = '不可用'
    break

  case 'en':
  default:
    // English (default) which is already set
    break
}

log('Language loaded: ' + detectedLocale)
